INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Cardiologia', 'Especialidade responsável pelo diagnóstico e tratamento de doenças do coração e sistema cardiovascular.', 'https://www.clinicasalute.com.br/upload/service/H44iBhjj04GNo8o6AiDauoRfXuwyRzzfD66eXeVK.jpeg');
INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Dermatologia', 'Especialidade voltada para prevenção, diagnóstico e tratamento de doenças da pele.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQvFQAEPqdO_Da6nfB1FI9WhEX_D5zDv2bw4bP-fVpHhflkysPQ0Sz5UE&s=10');
INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Pediatria', 'Especialidade médica dedicada ao acompanhamento da saúde de crianças e adolescentes.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVLlP_i_tn7-m2MiA71XxEpSDiqoA9IUsUZqGXjv615A&s=10');
INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Ortopedia', 'Especialidade responsável pelo tratamento de ossos, músculos, articulações e ligamentos.', 'https://ortoclinicaortopedia.com.br/wp-content/uploads/2025/09/imagem_2023-02-06_012305496-1024x810.png');
INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Neurologia', 'Especialidade que trata doenças do sistema nervoso central e periférico.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQY9oxPEkYFQizDTU23imwwziPJzRW49TWZHJDVEvEEhZtZvsVSHKlkkQw&s=10');
INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Oftalmologia', 'Especialidade voltada para o cuidado da visão e tratamento dos olhos.', 'https://www.pedempatia.com.br/wp-content/uploads/2022/02/clinica-pedempatia-oftalmologia-pediatra-para-criancas-cuidado-com-os-olhos.jpg');
INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Ginecologia', 'Especialidade dedicada à saúde do sistema reprodutor feminino.', 'https://www.apoenasaude.com.br/upload/service/shS4ip8jxfgWEjt1nAJKiRxlKsr7etnmRQfHxuOY.jpeg');
INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Psiquiatria', 'Especialidade focada na prevenção, diagnóstico e tratamento de transtornos mentais.', 'https://images.unsplash.com/photo-1573497620053-ea5300f94f21');
INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Endocrinologia', 'Especialidade responsável pelo tratamento de distúrbios hormonais e metabólicos.', 'https://images.unsplash.com/photo-1579684385127-1ef15d508118');
INSERT INTO tb_especialidades (id, nome, descricao, imagem_url) VALUES (UUID(), 'Urologia', 'Especialidade que trata doenças do trato urinário e sistema reprodutor masculino.', 'https://images.unsplash.com/photo-1516549655169-df83a0774514');
INSERT INTO tb_usuarios (id, nome, email, senha, foto, tipo_usuario, data_nascimento, cpf) VALUES (UUID(), 'Carlos', 'c@1', '1234', '', 'paciente', '2001-01-01', '14087160629');

INSERT INTO tb_usuarios (id, nome, email, senha, foto, tipo_usuario, data_nascimento, cpf) VALUES ('550e8400-e29b-41d4-a716-446655440000', 'Maria', 'm@g', '1234', '', 'medico', '2003-01-04', '12345678999');
INSERT INTO tb_medicos(usuario_id, crm, uf_emissao) VALUES('550e8400-e29b-41d4-a716-446655440000', '12441', 'MG');
